### ISSUE TITLE
Validation fails for files with only `---`

### ISSUE THREAD

**Issue by fuji8** [kubernetes-sigs/kubectl-validate#109]
### What happened?

Validating a file containing only `---` will cause validation to fail.

```console
❯ kubectl-validate has3hyphen.yaml 

has3hyphen.yaml...ERROR
GVK cannot be empty
Error: validation failed
```

### What did you expect to happen?

This file is essentially an empty file, and I expect the validation to succeed as well as a file containing only comments.

### How can we reproduce it (as minimally and precisely as possible)?

**has3hyphen.yaml**
```yaml
---

```

Validate the above file.
```console
❯ kubectl-validate has3hyphen.yaml 

has3hyphen.yaml...ERROR
GVK cannot be empty
Error: validation failed
```

### Kubernetes version

<details>

```console
❯ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

**Comment by alexzielenski** [comment]
I agree this is a bug. Lots of files by convention contain empty doccuments. We should ignore them

/label good-first-issue
/assign

**Comment by ah8ad3** [comment]
Hi @alexzielenski, i would like to take a look at this if its ok?
