### ISSUE TITLE
Support CRD lookup without a dependency on a running cluster

### ISSUE THREAD

**Issue by devantler** [kubernetes-sigs/kubectl-validate#131]
### What would you like to be added?

Allow CRDs to be looked from some centrally managed CRD store. I am not sure if that exists, but if it doesn't I believe it would be very valuable to support a more seamless user experience.

### Why is this needed?

I find linting fits best in use-cases where linting of manifests is done before applying manifest files to a cluster. This means that CRDs are not guaranteed to exist on the cluster, and thus pointing kubectl-validate towards a cluster isn't feasible.

Storing CRDs or OpenAPI schemas locally is also not a favorable option in this case, as that would require maintaining the CRDs separately, which Is somewhat cumbersome.

**Comment by devantler** [comment]
Maybe datreeio's CRD collection can be used? https://github.com/datreeio/CRDs-catalog

**Comment by baer95** [comment]
/reopen

I found this line in the code:
https://github.com/kubernetes-sigs/kubectl-validate/blob/main/pkg/cmd/validate.go#L195-L196

Could this feature be as simple as adding a condition to this line?
