### ISSUE TITLE
CI/CD And testing

### ISSUE THREAD

**Issue by apelisse** [kubernetes-sigs/kubectl-validate#2]
We probably need to set-up some CI/CD to validate pull-requests in that repo.

**Comment by eddycharly** [comment]
@apelisse do you want to use prow or gh actions ?

**Comment by apelisse** [comment]
prow is good because it's the official way of doing things in k8s. gh is good because the config is committed in the repo itself (easier to update and keep in sync with the repo). I would go with gh for now.

**Comment by apelisse** [comment]
This is fixed by #27
