### ISSUE TITLE
GitHub downloader is used even if local/hardcoded schemas are available

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes-sigs/kubectl-validate#22]
As it stands now the GitHub builtins downloader unconditionally attempts to fetch the schemas. We should make it so this only happens if there are no other schemas available, to avoid quickly exhausting rate limit unnecessarily

**Comment by clearnicki** [comment]
If this is available to work on - I can help with this.

/assign

**Comment by eddycharly** [comment]
Isn't it fixed by https://github.com/kubernetes-sigs/kubectl-validate/pull/26 ?

**Comment by alexzielenski** [comment]
> Isn't it fixed by #26 ?

Nope, this issue refers to the GitHub downloader always being unconditionally invoked by the `Composite` client. This can be fixed by creating a something like `FallbackClient(HardcodedSchemas, FetchGitHubSchemas)` that uses a fallback client if the primary client returned an error (like if the version is not supported by HardcodedSchemas).

**Comment by clearnicki** [comment]
@alexzielenski So #35 fixes this then? if so, I won't work on it. 

/unassign

**Comment by alexzielenski** [comment]
apologies @clearnicki this issue became a blocker for setting up CI

/close
