### ISSUE TITLE
check if connected cluster has specified version

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes-sigs/kubectl-validate#25]
Users connected to a cluster at version 1.27 but specify `--version 1.23` might be surprised when their cluster schemas override their chosen version. 

Possible approaches:

1. If version is specified, the cluster should only be consulted for builtin types when it matches the provided version.
2. If version is specified, cluster is ignored. If it is not specified, then will use a default hardcoded version only if cluster is not connected.

**Comment by stormqueen1990** [comment]
I'm interested in working on this, is it still available for picking up?
