### ISSUE TITLE
We need to create a "required" github workflow

### ISSUE THREAD

**Issue by apelisse** [kubernetes-sigs/kubectl-validate#28]
I've opened: https://github.com/kubernetes/test-infra/pull/29487
this mark the "required" job as required. Now we need to have a required job that depends on all the jobs that we want to see required.
cc @eddycharly

**Comment by apelisse** [comment]
This is similar to what we've done in kube-openapi with https://github.com/kubernetes/kube-openapi/pull/307

**Comment by alexzielenski** [comment]
is this done

**Comment by apelisse** [comment]
Yes
