### ISSUE TITLE
Unit Tests for Local Files Client

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes-sigs/kubectl-validate#43]
Currently have no unit tests for [`local_files.go`](https://github.com/kubernetes-sigs/kubectl-validate/blob/4f427a78cb5e0874c01587434a87cbb4869b9abf/pkg/openapiclient/local_files.go)

Would be nice to have some basic validation that it fetches the expected schemas and gives them back when asked for.

/assign @eddycharly 
(re: https://github.com/kubernetes-sigs/kubectl-validate/pull/40#issuecomment-1544552331)

**Comment by eddycharly** [comment]
@alexzielenski #46 only cover local crds client i think.
