### ISSUE TITLE
invalid manifest doesn't return non-zero exit code

### ISSUE THREAD

**Issue by eyarz** [kubernetes-sigs/kubectl-validate#61]
**steps to reproduce:**
1. pass `kubectl-validate` an invalid manifest
2. check `kubectl-validate` status code (`$?`)

**expected:**
non-zero exit code to indicate failure

**actual:**
the exit code is 0 (status has succeeded) 

![image](https://github.com/kubernetes-sigs/kubectl-validate/assets/19731161/7fde311f-03b3-4259-847e-888f527d07fb)

**Comment by MaGaroo** [comment]
Hey there!

May I work on it? It seems very beginner friendly.

**Comment by richardvflux** [comment]
would be very good to get this merged, just putting this into our CI pipelines and having a 0 exit on error is just a _little_ bit annoying. Very much appreciate the tool tho!

**Comment by richardvflux** [comment]
Any movement on this PR? Its making a pipeline somewhat awkward.

**Comment by alexzielenski** [comment]
#63 fixes this issue and has merged
