### ISSUE TITLE
Distribute pre-compiled binaries

### ISSUE THREAD

**Issue by aslafy-z** [kubernetes-sigs/kubectl-validate#71]
Distributing pre-compiled binaries would help the use in CI and [allow distributing it using krew](https://github.com/kubernetes-sigs/kubectl-validate/issues/70).

**Comment by eddycharly** [comment]
There was no release cut yet, it will probably happen once the tool is released.

**Comment by alexzielenski** [comment]
/close

Binaries are included in the release thanks to https://github.com/kubernetes-sigs/kubectl-validate/pull/76
