### ISSUE TITLE
Improve error handling in localSchemasClient

### ISSUE THREAD

**Issue by eddycharly** [kubernetes-sigs/kubectl-validate#75]
We should check directories exist and return an error if reading the directory returns an error in:

https://github.com/kubernetes-sigs/kubectl-validate/blob/76a49ca98743596967fec0d07c091b40144477ee/pkg/openapiclient/local_schemas.go#L35

https://github.com/kubernetes-sigs/kubectl-validate/blob/76a49ca98743596967fec0d07c091b40144477ee/pkg/openapiclient/local_schemas.go#L51

**Comment by hiroyaonoe** [comment]
I would like to work on this issue.
Do I simply return the error that ReadDir returns (with an additional message)?
Or should I do some kind of error handling?
/assign
